**개념 정리**

## 08. 텍스트 분석

NLP: 머신이 인간의 언어를 이해하고 해석하는 데 중점

텍스트 마이닝: 비정형 텍스트에서 의미 있는 정보를 추출하는 것에 중점
- 머신러닝, 언어 이해, 통계 등을 활용해 모델을 수립하고 정보를 추출해 비즈니스 인텔리전스나 예측 분석 등의 분석 작업을 주로 수행
- 텍스트 분류, 감성 분석, 텍스트 요약, 텍스트 군집화와 유사도 측정

### 01. 텍스트 분석 이해

텍스트 분석: 비정형 데이터인 텍스트를 분석하는 것
- 피처 벡터화(=피처 추출): 텍스트를 word 기반 다수의 피처로 추출하고 이 피처에 숫자 값을 부여하여 텍스트를 단어의 조합인 벡터값으로 표현
    - BOW, Word2Vec
- 텍스트 분석 수행 프로세스
    1. 텍스트 사전 준비 작업: 클렌징 작업, 토큰화 작업, 의미 없는 단어 제거 작업 등
    2. 피처 벡터화/추출: 사전 준비 작업으로 가공된 텍스트에서 피처를 추출하고 여기에 벡터 값을 할당
    3. ML 모델 수립 및 학습/예측/평가
- 파이썬 기반의 NLP, 텍스트 분석 패키지
    - NLTK, Gensim, SpaCy

### 02. 텍스트 사전 준비 작업(텍스트 전처리) - 텍스트 정규화

텍스트 정규화: 입력 데이터로 사용하기 위해 클렌징, 정제, 토큰화, 어근화 등 다양한 텍스트 데이터의 사전 작업을 수행하는 것
- 클렌징: 분석에 방해가 되는 불필요한 문자, 기호 등을 사전에 제거하는 작업
- 텍스트 토큰화
    - 문장 토큰화: 문서에서 문장을 분리
        - 문장의 마지막을 뜻하는 기호에 따라 분리하는 것이 일반적
    - 단어 토큰화: 문장에서 단어를 토큰으로 분리
        - 공백, 콤마, 마침표, 개행문자 등으로 분리하는 것이 일반적
        - 단어의 순서가 중요하지 않은 경우 단어 토큰화만 사용해도 충분
        - n-gram: 연속된 n개의 단어를 하나의 토큰화 단위로 분리해 내는 것
- 스톱 워드 제거
    - 스톱 워드: 분석에 큰 의미가 없는 단어
- Stemming과 Lemmatization
    - 원형 단어를 찾는다는 목적을 가짐
    - Stemming: 원형 단어로 변환 시 일반적인 or 단순화된 방법을 적용해 원래 단어에서 일부 철자가 훼손된 어근 단어를 추출하는 경향
        - Porter, Lancaster, Snowball Stemmer
    - Lemmatization: 품사와 같은 문법적인 요소와 더 의미적인 부분을 감안해 정확한 철자로 된 어근 단어를 찾아줌
        - WordNetLemmatizer

### 03. Bag of Words - BOW

Bag of Words: 문서가 가지는 모든 단어를 문맥이나 순서를 무시하고 일괄적으로 단어에 대해 빈도 값을 부여해 피처 값을 추출하는 모델
- BOW 장단점
    - 장점: 쉽고 빠른 구축
    - 단점: 문맥 의미 반영 부족, 희소 행렬 문제
- BOW 피처 벡터화: 모든 문서에서 모든 단어를 칼럼 형태로 나열하고 각 문서에서 해당 단어의 횟수나 정규화된 빈도를 값으로 부여하는 데이터 세트 모델로 변경하는 것

- BOW 피처 벡터화 방식
    - 카운트 기반의 벡터화: 해당 단어가 나타나는 횟수를 부여
        - CountVectorizer: 피처 벡터화 + 소문자 일괄 변환, 토큰화, 스톱워드 필터링
            - 파라미터: max_df, min_df, max_features, stop_words, n_gram_range, analyzer, token_pattern, tokenizer
            1. 영어의 경우 모든 문자를 소문자로 변경하는 등의 전처리 작업 수행
            2. 디폴트로 단어 기준으로 n_gram_range를 반영해 각 단어를 토큰화
            3. 텍스트 정규화 수행
            4. 피처 벡터화
    - TF-IDF: 개별 문서에서 자주 나타나는 단어에 높은 가중치를 주되, 모든 문서에서 전반적으로 자주 나타나는 단어에 대해서 페널티 부여
        - TfidfVectorizer: 파라미터와 변환 방법이 CountVectorizer과 동일

- BOW 벡터화를 위한 희소 행렬
    - 희소 행렬: 대규모 행렬의 대부분의 값을 0이 차지하는 행렬
        - 메모리 공간이 많이 필요, 데이터 액세스를 위한 시간이 많이 소모
    - COO 방식: 0이 아닌 데이터만 별도의 데이터 배열에 저장하고, 그 데이터가 가리키는 행과 열의 위치를 별도의 배열로 저장
    - CSR 방식: 행 위치 배열 내에 있는 고유한 값의 시작 위치만 다시 별도의 위치 배열로 가지는 변환 방식
        - COO 형식이 행과 열의 위치를 나타내기 위해서 반복적인 위치 데이터를 사용해야 하는 문제점을 해결

**코드 필사**

### 02.

In [ ]:
from nltk import sent_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

text_sample='The Matrix is everywhere its all around us, here even in this room. \
            You can see it out your window or on your television. \
            You feel it when you go to work, or go to church or pay your taxes.'
sentences=sent_tokenize(text=text_sample)
print(type(sentences), len(sentences))
print(sentences)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']


In [ ]:
from nltk import word_tokenize

sentence="The Matrix is everywhere its all around us, here even in this room."
words=word_tokenize(sentence)
print(type(words), len(words))
print(words)

<class 'list'> 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


In [ ]:
from nltk import word_tokenize, sent_tokenize

#여러 개의 문장으로 된 입력 데이터를 문장 별로 단어 토큰화하게 만드는 함수 생성
def tokenize_text(text):

    #문장 별로 분리 토큰
    sentences=sent_tokenize(text)
    #분리된 문장 별 단어 토큰화
    word_tokens=[word_tokenize(sentence) for sentence in sentences]
    return word_tokens

#여러 문장에 대해 문장 별 단어 토큰화 수행
word_tokens=tokenize_text(text_sample)
print(type(word_tokens), len(word_tokens))
print(word_tokens)

<class 'list'> 3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
print('영어 stop words 개수:', len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:20])

영어 stop words 개수: 198
['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been']


In [ ]:
import nltk

stopwords=nltk.corpus.stopwords.words('english')
all_tokens=[]
#위 예제에서 3개의 문장 별로 얻은 word_tokens list에 대해 스톱 워드를 제거하는 반복문
for sentence in word_tokens:
    filtered_words=[]
    #개별 문장 별로 토큰화된 문장 list에 대해 스톱 워드를 제거하는 반복문
    for word in sentence:
        #소문자로 모두 변환합니다.
        word=word.lower()
        #토큰화된 개별 단어가 스톱 워드의 단어에 포함되지 않으면 word_tokens에 추가
        if word not in stopwords:
            filtered_words.append(word)
    all_tokens.append(filtered_words)

print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]


In [ ]:
from nltk.stem import LancasterStemmer
stemmer=LancasterStemmer()

print(stemmer.stem('working'), stemmer.stem('works'), stemmer.stem('worked'))
print(stemmer.stem('amusing'), stemmer.stem('amuses'), stemmer.stem('amused'))
print(stemmer.stem('happier'), stemmer.stem('happiest'))
print(stemmer.stem('fancier'), stemmer.stem('fanciest'))

work work work
amus amus amus
happy happiest
fant fanciest


In [ ]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')

lemma=WordNetLemmatizer()
print(lemma.lemmatize('amusing', 'v'), lemma.lemmatize('amuses', 'v'), lemma.lemmatize('amused', 'v'))
print(lemma.lemmatize('happier', 'a'), lemma.lemmatize('happiest', 'a'))
print(lemma.lemmatize('fancier', 'a'), lemma.lemmatize('fanciest', 'a'))

[nltk_data] Downloading package wordnet to /root/nltk_data...


amuse amuse amuse
happy happy
fancy fancy


### 03.

In [ ]:
import numpy as np

dense=np.array([[3,0,1], [0,2,0]])

In [ ]:
from scipy import sparse

#0이 아닌 데이터 추출
data=np.array([3,1,2])

#행 위치와 열 위치를 각각 배열로 생성
row_pos=np.array([0,0,1])
col_pos=np.array([0,2,1])

#sparse 패키지의 coo_matrix를 이용해 COO 형식으로 희소 행렬 생성
sparse_coo=sparse.coo_matrix((data, (row_pos, col_pos)))

In [ ]:
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

In [ ]:
[[0,0,1,0,0,5], [1,4,0,3,2,5], [0,6,0,3,0,0], [2,0,0,0,0,0], [0,0,0,7,0,8], [1,0,0,0,0,0]]

[[0, 0, 1, 0, 0, 5],
 [1, 4, 0, 3, 2, 5],
 [0, 6, 0, 3, 0, 0],
 [2, 0, 0, 0, 0, 0],
 [0, 0, 0, 7, 0, 8],
 [1, 0, 0, 0, 0, 0]]

In [ ]:
from scipy import sparse

dense2=np.array([[0, 0, 1, 0, 0, 5],
                [1, 4, 0, 3, 2, 5],
                [0, 6, 0, 3, 0, 0],
                [2, 0, 0, 0, 0, 0],
                [0, 0, 0, 7, 0, 8],
                [1, 0, 0, 0, 0, 0]])

#0이 아닌 데이터 추출
data2=np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])

#행 위치와 열 위치를 각각 array로 생성
row_pos=np.array([0,0,1,1,1,1,1,2,2,3,4,4,5])
col_pos=np.array([2,5,0,1,3,4,5,1,3,0,3,5,0])

#COO 형식으로 변환
sparse_coo=sparse.coo_matrix((data2, (row_pos, col_pos)))

#행 위치 배열의 고유한 값의 시작 위치 인덱스를 배열로 생성
row_pos_ind=np.array([0,2,7,9,10,12,13])

#CRS 형식으로 변환
sparse_csr=sparse.csr_matrix((data2, col_pos, row_pos_ind))

print('COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_coo.toarray())
print('CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_coo.toarray())

COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [ ]:
dense3=np.array([[0, 0, 1, 0, 0, 5],
                [1, 4, 0, 3, 2, 5],
                [0, 6, 0, 3, 0, 0],
                [2, 0, 0, 0, 0, 0],
                [0, 0, 0, 7, 0, 8],
                [1, 0, 0, 0, 0, 0]])

coo=sparse.coo_matrix(dense3)
csr=sparse.csr_matrix(dense3)